/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semanticnet;


import com.sun.org.apache.xpath.internal.operations.Variable;
import static java.nio.file.Files.size;
import semanticnet.Endpoint;
import semanticnet.EndpointException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
/**
 *
 */
public class Pencere extends javax.swing.JFrame {

    /**
     * Creates new form Pencere
     */
    public Pencere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Kemal Sunal'ın oynadığı 30 film");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 329, 50));

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setText("David Yates' in yönettiği 10 film");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 329, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Vin Diesel'in oynadığı 10 film");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 50));

        jButton4.setBackground(new java.awt.Color(204, 204, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText("Nuri Bilge Ceylan 'ın yönettiği flimler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 330, 50));

        jButton8.setBackground(new java.awt.Color(204, 204, 0));
        jButton8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton8.setText("Karayip Korsanları");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 330, 50));

        jButton7.setBackground(new java.awt.Color(204, 204, 0));
        jButton7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton7.setText("Ezgi Mola 'nın oynadığı filmler");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, 50));

        jButton5.setBackground(new java.awt.Color(204, 204, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("Yeşim Ustaoglu 'nun yönettiği filmler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 330, 50));

        jButton9.setBackground(new java.awt.Color(204, 204, 0));
        jButton9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton9.setText("Batman");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 330, 50));

        jButton10.setBackground(new java.awt.Color(204, 204, 0));
        jButton10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton10.setText("Temizle");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 958, 53));

        jButton6.setBackground(new java.awt.Color(204, 204, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton6.setText("Hızlı ve Öfkeli");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 330, 50));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 950, 250));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("OYUNCULAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("YÖNETMENLER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("FİLM SERİLERİ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?oyuncu ?oyuncuLabel\n" +
                "where{\n" +
                "?oyuncu wdt:P161 wd:Q735585.\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "LIMIT 30";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?oyuncu ?oyuncuLabel \n" +
                "where{\n" +
                "?oyuncu wdt:P161 wd:Q178166 \n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],en\". }\n" +
                "}\n" +
                "LIMIT 10";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        jTextArea1.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?film ?filmLabel \n" +
                "where{\n" +
                "?film wdt:P179 wd:Q2111133\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "\n" +
                "";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?film ?filmLabel \n" +
                "where{\n" +
                "?film wdt:P179 wd:Q194318\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "\n" +
                "";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?oyuncu ?oyuncuLabel \n" +
                "where{\n" +
                "?oyuncu wdt:P161 wd:Q5423258 \n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "LIMIT 10";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?film ?filmLabel \n" +
                "where{\n" +
                "?film wdt:P179 wd:Q1576873\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?yonetmen ?yonetmenLabel\n" +
                "where{\n" +
                "?yonetmen wdt:P57 wd:Q536298\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect ="select ?yonetmen ?yonetmenLabel\n" +
                "where{\n" +
                "?yonetmen wdt:P57 wd:Q724172\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],tr\". }\n" +
                "}\n" +
                "";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String endpointUrl = "https://query.wikidata.org/sparql";

        String querySelect = "select ?yonetmen ?yonetmenLabel\n" +
                "where{\n" +
                "?yonetmen wdt:P57 wd:Q312988\n" +
                "SERVICE wikibase:label { bd:serviceParam wikibase:language \"[AUTO_LANGUAGE],en\". }\n" +
                "}\n" +
                "LIMIT 15";

        try {
            HashMap data = retrieveData(endpointUrl, querySelect);
            printResult(data, 30);
        } catch (EndpointException eex) {
            eex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    public static HashMap<String, HashMap> retrieveData(String endpointUrl, String query) throws EndpointException {
        Endpoint sp = new Endpoint(endpointUrl, false);
        HashMap<String, HashMap> rs = sp.query(query);
        return rs;
    }

    public void printResult(HashMap<String, HashMap> rs , int size) {
     

        for (String variable : (ArrayList<String>) rs.get("result").get("variables")) {
        jTextArea1.append(String.format("%-"+size+"."+size+"s", variable ) + " | ");
     //  System.out.print(String.format("%-"+size+"."+size+"s", variable ) + " | ");
      }
      System.out.print("\n");
      for (HashMap value : (ArrayList<HashMap>) rs.get("result").get("rows")) {
          
           jTextArea1.append("\n");
        for (String variable : (ArrayList<String>) rs.get("result").get("variables")) {
          jTextArea1.append(String.format("%-"+size+"."+size+"s", value.get(variable)) + " | ");
       //System.out.print(String.format("%-"+size+"."+size+"s", value.get(variable)) + " | ");
        }
       
      }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
               
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencere().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    
    
    
}
